node('ecs') {
    stage('Clone git repo') { 
        cleanWs()
        git url: 'https://github.com/kzl86/mvp-lab.git', branch: 'main'
    }
	stage('Initialize ECS') {
		withCredentials([string(credentialsId: 'MYSQL_WORDPRESS_PASSWORD', variable: 'mysql_wordpress_password')]) {
			dir('ecs/init') {			
				sh script: 'chmod +x ./modify.sh && sudo ./modify.sh $inputAddress $mysql_wordpress_password $inputAddress2'
			}
		}
	}
}