node('mysql') {
    stage('Clone git repo') { 
        cleanWs()
        git url: 'https://github.com/kzl86/mvp-lab.git', branch: 'main'
    }
	stage('Prepare MySQL for Wordpress') {
						dir('mysql/wordpress') {
							sh script: 'chmod +x ./prepareWordpress.sh && sudo ./prepareWordpress.sh $MYSQL_PASSWORD "$MYSQL_WORDPRESS_PASSWORD" '
			}
	}
}